// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dhia.com.domain;

import dhia.com.domain.Adress_particulierIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Adress_particulierIntegrationTest_Roo_Configurable {
    
    declare @type: Adress_particulierIntegrationTest: @Configurable;
    
}
