// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dhia.com.domain;

import dhia.com.domain.Categorie_metierIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Categorie_metierIntegrationTest_Roo_Configurable {
    
    declare @type: Categorie_metierIntegrationTest: @Configurable;
    
}
