// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dhia.com.domain;

import dhia.com.domain.Doc_userIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Doc_userIntegrationTest_Roo_Configurable {
    
    declare @type: Doc_userIntegrationTest: @Configurable;
    
}
