// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dhia.com.domain;

import dhia.com.domain.MapsDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect MapsDataOnDemand_Roo_Configurable {
    
    declare @type: MapsDataOnDemand: @Configurable;
    
}
