// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dhia.com.domain;

import dhia.com.domain.Metier_detailIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Metier_detailIntegrationTest_Roo_Configurable {
    
    declare @type: Metier_detailIntegrationTest: @Configurable;
    
}
