// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dhia.com.domain;

import dhia.com.domain.Old_loginDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Old_loginDataOnDemand_Roo_Configurable {
    
    declare @type: Old_loginDataOnDemand: @Configurable;
    
}
