// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dhia.com.domain;

import dhia.com.ServiceUsers;
import dhia.com.domain.UsersDataOnDemand;
import dhia.com.domain.UsersIntegrationTest;
import java.math.BigInteger;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

privileged aspect UsersIntegrationTest_Roo_IntegrationTest {
    
    declare @type: UsersIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: UsersIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    @Autowired
    UsersDataOnDemand UsersIntegrationTest.dod;
    
    @Autowired
    ServiceUsers UsersIntegrationTest.serviceUsers;
    
    @Test
    public void UsersIntegrationTest.testCountAllUserses() {
        Assert.assertNotNull("Data on demand for 'Users' failed to initialize correctly", dod.getRandomUsers());
        long count = serviceUsers.countAllUserses();
        Assert.assertTrue("Counter for 'Users' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void UsersIntegrationTest.testFindUsers() {
        Users obj = dod.getRandomUsers();
        Assert.assertNotNull("Data on demand for 'Users' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Users' failed to provide an identifier", id);
        obj = serviceUsers.findUsers(id);
        Assert.assertNotNull("Find method for 'Users' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Users' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void UsersIntegrationTest.testFindAllUserses() {
        Assert.assertNotNull("Data on demand for 'Users' failed to initialize correctly", dod.getRandomUsers());
        long count = serviceUsers.countAllUserses();
        Assert.assertTrue("Too expensive to perform a find all test for 'Users', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Users> result = serviceUsers.findAllUserses();
        Assert.assertNotNull("Find all method for 'Users' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Users' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void UsersIntegrationTest.testFindUsersEntries() {
        Assert.assertNotNull("Data on demand for 'Users' failed to initialize correctly", dod.getRandomUsers());
        long count = serviceUsers.countAllUserses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Users> result = serviceUsers.findUsersEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Users' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Users' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void UsersIntegrationTest.testSaveUsers() {
        Assert.assertNotNull("Data on demand for 'Users' failed to initialize correctly", dod.getRandomUsers());
        Users obj = dod.getNewTransientUsers(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Users' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Users' identifier to be null", obj.getId());
        try {
            serviceUsers.saveUsers(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        Assert.assertNotNull("Expected 'Users' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void UsersIntegrationTest.testDeleteUsers() {
        Users obj = dod.getRandomUsers();
        Assert.assertNotNull("Data on demand for 'Users' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Users' failed to provide an identifier", id);
        obj = serviceUsers.findUsers(id);
        serviceUsers.deleteUsers(obj);
        Assert.assertNull("Failed to remove 'Users' with identifier '" + id + "'", serviceUsers.findUsers(id));
    }
    
}
