// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dhia.com.domain;

import dhia.com.domain.Categorie_metier;

privileged aspect Categorie_metier_Roo_JavaBean {
    
    public String Categorie_metier.getName() {
        return this.name;
    }
    
    public void Categorie_metier.setName(String name) {
        this.name = name;
    }
    
}
