// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package dhia.com.domain;

import dhia.com.domain.Old_login;

privileged aspect Old_login_Roo_JavaBean {
    
    public String Old_login.getLastpassword() {
        return this.lastpassword;
    }
    
    public void Old_login.setLastpassword(String lastpassword) {
        this.lastpassword = lastpassword;
    }
    
}
